package com.system.model;

public enum GradeLevels {
    FIRST_FUNDAMENTAL,
    SECOND_FUNDAMENTAL,
    THIRD_FUNDAMENTAL,
    FOURTH_FUNDAMENTAL,
    FIFTH_FUNDAMENTAL,
    SIXTH_FUNDAMENTAL,
    SEVENTH_FUNDAMENTAL,
    EIGHTH_FUNDAMENTAL,
    NINTH_FUNDAMENTAL,
    FIRST_COLLEGIUM,
    SECOND_COLLEGIUM,
    THIRD_COLLEGIUM,
}
